### ISSUE TITLE
我想加入

### ISSUE THREAD

**Issue by hanmichael** [android-cn/android-jobs#227]
你好， 我想加入， 谢谢啦

**Comment by dkmeteor** [comment]
@hanmichael 

https://github.com/android-cn/android-jobs/wiki/%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E8%81%8C%E4%BD%8D%E5%8F%8A%E5%86%85%E5%AE%B9%E8%A7%84%E8%8C%83
