### ISSUE TITLE
二维码模糊，排版完全错乱！！！！

### ISSUE THREAD

**Issue by D-clock** [android-cn/android-jobs#266]
如下图：

![](https://diycode.b0.upaiyun.com/photo/2017/9f1e5a51d4cb1e179ff82aa592571a2b.png)

![](https://diycode.b0.upaiyun.com/photo/2017/52eb2a0e8f0c71368830d7db4098c84e.png)

![](https://diycode.b0.upaiyun.com/photo/2017/4c7c766d7c013b8d848c9e90bab12790.png)

迷之尴尬！！！！！！！！！！！！！

**Comment by githubwing** [comment]
![image](https://cloud.githubusercontent.com/assets/12854998/25077005/9a47a226-2358-11e7-9fe7-b49aec5c738a.png)
我这里没有问题 你的网络？

**Comment by D-clock** [comment]
我网络正常啊，，秒开，其他Project的README正常！

**Comment by XConstantine** [comment]
排版的确乱了，但我这二维码可以正常加载出来
@D-clock 少年你是不是撸多了看的这么模糊[奸笑]

**Comment by dkmeteor** [comment]
同上

顺便源码我复制到第三方MD工具里看  格式正常
github的表格语法是不是更新了?

**Comment by Trinea** [comment]
上周 GitHub 更新了 MD 的规范支持，浏览器没有缓存的话最新的格式确实是乱的，最近略忙，回头等我确认新的语法不影响 [codeKK](http://j.codekk.com/) 的同步会对这里做修改。
